install.packages("devtools")
library(devtools)
devtools::install_github("DataComputing/DataComputing")
install.packages(c("tidyverse","knitr","rmarkdown","rpart","shiny","manipulate"))
install.packages(c("mosaic","mosaicData","NHANES"))